### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by AdityaAnand1** [toluaina/pg-sync#24]
![image](https://user-images.githubusercontent.com/13274079/86227810-3ae35480-bbab-11ea-8c8d-9393f22e264b.png)

My docker yaml

```

services:
  postgres:
    image: debezium/postgres:12-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=pgsync
      - POSTGRES_PASSWORD=pgsync
      - POSTGRES_DB=pgsync
  redis:
    image: redis
    command: redis-server
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - xpack.security.enabled=false
      - network.host=127.0.0.1
      - http.host=0.0.0.0
  pgsync:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./runserver.sh
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to elasticsearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - postgres
      - redis
      - elasticsearch
    environment:
      - PG_USER=pgsync
      - PG_HOST=postgres
      - PG_PASSWORD=pgsync
      - LOG_LEVEL=INFO
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_SCHEME=http
      - ELASTICSEARCH_HOST=elasticsearch
      - REDIS_HOST=redis
      - REDIS_AUTH=
```
